name: Maven Workflow

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 14

    - name: Build project with Maven
      run: mvn -B package --file pom.xml
